name: Update JSON

on:
  push:
    branches:
      - main  # o master, dipende da come si chiama il tuo branch principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: |
          python downloader.py

      - name: Commit and push generated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pokemon_list.json
          git commit -m "Update JSON [skip ci]" || echo "No changes to commit"
          git push